aa: rand-m9-mstd0.5-inc1
amp: true
apex_amp: false
aug_repeats: 0
aug_splits: 0
batch_size: 32
bce_loss: false
bce_target_thresh: null
bn_eps: null
bn_momentum: null
channels_last: false
checkpoint_hist: 1
class_map: ''
clip_grad: null
clip_mode: norm
color_jitter: 0.4
contrast_aug: false
contrastive: false
cooldown_epochs: 10
crop_pct: null
cutmix: 0.0
cutmix_minmax: null
data_dir: /home/yhr/GPS1/data/vtab/vtab-1k/kitti
dataset:
- kitti
dataset_download: false
decay_epochs: 100
decay_milestones:
- 30
- 60
decay_rate: 0.1
direct_resize: true
dist_bn: reduce
drop: 0.0
drop_block: null
drop_connect: null
drop_path: 0.0
epoch_repeats: 0.0
epochs: 100
eval_metric: top1
evaluate: false
experiment: vtab
fuser: ''
gp: null
gpu_id: '2'
grad_checkpointing: false
head_reparam: true
hflip: 0.5
img_size: 224
init_lr: true
initial_checkpoint: ''
input_size: null
interpolation: ''
jsd_loss: false
keep_rate: 0.95
layer_decay: null
local_rank: 0
log_interval: 200
log_wandb: true
lr: 0.0006
lr_cycle_decay: 0.5
lr_cycle_limit: 1
lr_cycle_mul: 1.0
lr_k_decay: 1.0
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
mean: null
min_lr: 1.0e-08
mixup: 0.0
mixup_mode: batch
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_switch_prob: 0.5
model: vit_base_patch16_224_in21k
model_ema: false
model_ema_decay: 0.9998
model_ema_force_cpu: false
momentum: 0.9
native_amp: false
no_aug: true
no_ddp_bb: false
no_prefetcher: true
no_resume_opt: false
num_classes: 4
num_classes_list: null
opt: adam
opt_betas: null
opt_eps: null
output: 5811_output/0.95_kitti_output/
patience_epochs: 10
pin_mem: false
pretrained: true
pruning: true
pruning_method: gradient_perCell
ratio:
- 0.75
- 1.3333333333333333
recount: 1
recovery_interval: 0
remode: pixel
reprob: 0.25
resplit: false
resume: ''
run_name: ''
save_images: false
scale:
- 0.08
- 1.0
sched: cosine
seed: 42
simple_aug: false
smoothing: 0.0
split_bn: false
start_epoch: null
std: null
sync_bn: false
times_para: 15
top_param: 0.03
torchscript: false
train_interpolation: random
train_split: train
tta: 0
tuning_mode: part
use_lr: false
use_multi_epochs_loader: false
val_split: validation
validation_batch_size: 128
vflip: 0.0
warmup_epochs: 20
warmup_lr: 0.004
weight_decay: 0.0
worker_seeding: all
workers: 8
